/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Vendedor;

/**
 *
 * @author CHARLES
 */
public class ListaVendedorJF extends javax.swing.JFrame {

    ArrayList<Vendedor> listaVendedores;
    /**
     * Creates new form ListaVendedorJF
     */
    public ListaVendedorJF() {
        initComponents();
        listaVendedores = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstVendedor = new javax.swing.JList<>();
        btnAddVendedor = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstVendedor.setModel(new javax.swing.DefaultListModel<Vendedor>()
        );
        jScrollPane1.setViewportView(lstVendedor);

        btnAddVendedor.setText("Adicionar");
        btnAddVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVendedorActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddVendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(29, 29, 29)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVendedor)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVendedorActionPerformed
        CadastroVendedorDialog dialog = new CadastroVendedorDialog(this, true);
        dialog.setVisible(true);
        
        Vendedor novoVendedor = dialog.getVendedor();
        listaVendedores.add(novoVendedor);
        
        JOptionPane.showMessageDialog(null, "Vendedor Cadastrado: "+novoVendedor);   
        
        loadItensInList();
    }//GEN-LAST:event_btnAddVendedorActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Vendedor vendedorSelecionado = lstVendedor.getSelectedValue();
        if(vendedorSelecionado != null){
            
            CadastroVendedorDialog dialog = new CadastroVendedorDialog(this, true);
            dialog.setVendedor(vendedorSelecionado);
            dialog.setVisible(true);
            
            loadItensInList();
            
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um item", 
                    "Produto não selecionado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        Vendedor vendedorSelecionado = lstVendedor.getSelectedValue();
        if(vendedorSelecionado != null){
            
            int remover = JOptionPane.showConfirmDialog(rootPane, 
                    "Tem certeza que deseja excluir o vendedor "+vendedorSelecionado.getNome()+"?");
            
            if(remover == JOptionPane.YES_OPTION){
                listaVendedores.remove(vendedorSelecionado);
                loadItensInList();
            }
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um vendedor", 
                    "Vendedor não selecionado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    public void loadItensInList(){
        DefaultListModel modeloLista = new DefaultListModel();
        modeloLista.removeAllElements();
        for(Vendedor v: listaVendedores){
            modeloLista.addElement(v.getNome() + " - " + v.getCPF());
        }
        
        lstVendedor.setModel(modeloLista);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaVendedorJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaVendedorJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaVendedorJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaVendedorJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaVendedorJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVendedor;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Vendedor> lstVendedor;
    // End of variables declaration//GEN-END:variables
}
